version: "2"
services:
  web1:
    build: ./app
    volumes:
      - "./app:/app"
    ports:
      - "3000:3000"
    command: nodemon -L bin/www
    links:
      - db
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web1
    links:
      - web1:web1

  db:
    image: mongo
    ports:
        - "27017"

  redis:
    image: redis
    ports:
        - "6379"
